Sprint 1/step 2
Some-0ne-Else/react-burger pull request #3
Opened 2021-06-28 10:44 UTC by Some-0ne-Else

2021-06-28 20:46 UTC, SmilingJey requested changes
Здравствуйте, Александр!

Хорошая работа, приложение почти полностью соответсвует макету, необходимый функционал работает, реализовано открытие попапа в портале. Но есть несколько замечаний:

**Нужно исправить:**

- обработка закрытия по ESC должна быть описана в компоненте Modal

- Modal нужно рендерить только если модальное окно открыто, пропс isOpen не нужен

- имена констант принято записывать в стиле UPPER_CASE

- убрать синюю обводку у блоков, эта обводка на макете нужна только что бы сделать опаисание поясняющее к этому блоку

**Места, в которых можно улучшить проект:**

- вынести  функцию запрос  к серверу в отдельный файл

- вычисления следует обернуть в useMemo, что бы они выполнялись только при изменении данных, а не при каждом рендере

- при клике на соответвующий таб должен происходить скрол к нужному разделй в списке

- не делайте вычисления внутри JSX  получите все данные перед разметкой, а потом используйте эти данные, пример привел на основе фильтрации ингредиентов

- поместите ModalOverlay внутри Modal, а не добавляйте отдельно на страницу

- не имеет смысла передавать стрелочную функуцию, если можно просто записать onClick={onClose}

- исправить отклонения от макета, которые отмечены на скриншоте

Подробнее замечания описаны ниже в комментариях к самим участкам кода:


![Screenshot_58](https://user-images.githubusercontent.com/9317133/123701825-07451400-d86b-11eb-8f32-316de9b66ed6.png)

2021-06-28 20:46 UTC, SmilingJey commented on src/components/App/App.jsx
> +    fetch(ingredientsUrl)
**Можно лучше**

создайте отдельный файл burger-api в utils и опишите в нем все функции запросов

Например

```
const getIngredients = () => {
    return fetch(ingredientsUrl)
      .then((res) => {
        if (res.ok) {
          return res.json();
        }
        throw new Error(`Error ${res.status}`)
      })
}
```

 это удобнее, чем писать каждый запрос в компоненте

2021-06-28 20:46 UTC, SmilingJey commented on src/components/BurgerConstructor/BurgerConstructor.jsx
>    const total = data.reduce((acc, el) => { return el.price + acc }, 0)
**Можно лучше**

вычисления следует обернуть в useMemo, что бы они выполнялись только при изменении данных, а не при каждом рендере

2021-06-28 20:46 UTC, SmilingJey commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    if (e.code !== "Escape" && e.type === "keydown") { return }
**Надо исправить**

закрытие попапа по ESC (навешивание и удаление обработчика, проверка назатой клавиши) относится к функционалу компонента Modal и должно быть описано в нем, а не в констукторе бургера

Обработчик должен вешаться при монтировании компонента и удаляться при размонтировании

2021-06-28 20:46 UTC, SmilingJey commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      <Modal isOpen={isModalOpened} onClose={closeModal}>
**Надо исправить**

Modal нужно рендерить только если модальное окно открыто


```
      {isModalOpened && (
      <Modal onClose={closeModal}>
          <OrderDetails orderId={orderId} />
      </Modal>
     <ModalOverlay onClose={closeModal} />)}
```

2021-06-28 20:46 UTC, SmilingJey commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    if (e.code !== "Escape" && e.type === "keydown") { return }
**Надо исправить**

закрытие попапа по ESC (навешивание и удаление обработчика, проверка назатой клавиши) относится к функционалу компонента Modal и должно быть описано в нем, а не в констукторе бургера

Обработчик должен вешаться при монтировании компонента и удаляться при размонтировании

2021-06-28 20:46 UTC, SmilingJey commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +      <Modal title={"Детали ингредиента"} isOpen={isModalOpened} onClose={closeModal}>
**Надо исправить**

Modal нужно рендерить только если модальное окно открыто


```
      {isModalOpened && (
      <Modal title={"Детали ингредиента"} onClose={closeModal}>
        <IngredientDetails
          name={currentIngredient.name}
          image={currentIngredient.image_large}
          calories={currentIngredient.calories}
          proteins={currentIngredient.proteins}
          fat={currentIngredient.fat}
          carbohydrates={currentIngredient.carbohydrates}
        />
      </Modal>
     <ModalOverlay onClose={closeModal} />)}
```

2021-06-28 20:46 UTC, SmilingJey commented on src/components/BurgerIngredients/BurgerIngredients.jsx
>    const [current, setCurrent] = React.useState('one')
**Можно лучше**

- дайте более информативные значения, вместо one two tree - buns mains sauces

- при клике на соответвующий таб должен происходить скрол к нужному разделй в списке

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:
```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };
```
где заголовкам разделов заданы соответсвующие атрибуты id 

https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2021-06-28 20:46 UTC, SmilingJey commented on src/components/IngredientsList/IngredientsList.jsx
>    const filterByType = (type) => {
**Можно лучше**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив. Например:

```
const buns = useMemo(data.filter((item) => item.type === 'buns'), [data]);

return (
   ....................
   buns.map(....................)
   ..................
)
```

Так же используйте используйте  useMemo, что бы фильтрация не вызывалась при каждом ренедере

2021-06-28 20:46 UTC, SmilingJey commented on src/components/Modal/Modal.jsx
> +function Modal({ title, isOpen, onClose, children }) {
**Надо исправаить**

передаваемый колбэк onClose должен только закрывать окно

А обработка закрытия по ESC должна быть описана в этом компоненте, при монтировании компонента должен вешаться обработчик, а при размонтировании удаляться

2021-06-28 20:46 UTC, SmilingJey commented on src/components/ModalOverlay/ModalOverlay.jsx
> +        <div onClick={(e)=> onClose(e)} className={styles.overlay}></div>
**Можно лучше**

не имеет смысла в данном случае передавать стрелочную функуцию, можно просто` onClick={onClose}`

2021-06-28 20:46 UTC, SmilingJey commented on src/components/Modal/Modal.jsx
> +
**Можно лучше**

поместите ModalOverlay внутри Modal, а не добавляйте отдельно на страницу


```
    return ReactDOM.createPortal((
        <>
        <div className={isOpen ? `${styles.modal} ${styles.modal_opened}` : `${styles.modal}`}>
        <div className={`${styles.modal__container} mr-10 mt-10 ml-10`}>
            <p className={`${styles.modal__title} text text_type_main-large`}>{title}</p>
            <button type="button" onClick={(e)=> onClose(e)} className={`${styles.modal__button}`}><CloseIcon type="primary" /></button>
            </div>
            {children}
        </div>
        <ModalOverlay onClose={onClose} />
        </>
    ), modalRoot)
}
```

2021-06-28 20:46 UTC, SmilingJey commented on src/components/Modal/Modal.jsx
> +        <div className={isOpen ? `${styles.modal} ${styles.modal_opened}` : `${styles.modal}`}>
**Надо исправить**

не нужен пропс isOpen, т.к. если окно рендерится то оно должно быть открыто, если не рендерится то не отображается

2021-06-29 11:31 UTC, Some-0ne-Else commented on src/utils/constants.js
> +const ingredientsUrl = 'https://norma.nomoreparties.space/api/ingredients';
Исправлено

2021-06-29 11:38 UTC, Some-0ne-Else commented on src/components/App/App.jsx
> +    fetch(ingredientsUrl)
Вынесено в burger-api

2021-06-29 11:42 UTC, Some-0ne-Else commented on src/components/BurgerConstructor/BurgerConstructor.jsx
>    const total = data.reduce((acc, el) => { return el.price + acc }, 0)
Отлично, появилось больше понимания когда использовать

2021-06-29 11:48 UTC, Some-0ne-Else commented on src/components/Modal/Modal.jsx
> +
Исправлено

2021-06-29 11:56 UTC, Some-0ne-Else commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      <Modal isOpen={isModalOpened} onClose={closeModal}>
Логично =) Исправлено

2021-06-29 12:00 UTC, Some-0ne-Else commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    if (e.code !== "Escape" && e.type === "keydown") { return }
Добавился новый подход, спасибо!

2021-06-29 12:01 UTC, Some-0ne-Else commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    if (e.code !== "Escape" && e.type === "keydown") { return }
Исправлено

2021-06-29 12:02 UTC, Some-0ne-Else commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +      <Modal title={"Детали ингредиента"} isOpen={isModalOpened} onClose={closeModal}>
Исправлено

2021-06-29 13:57 UTC, Some-0ne-Else commented on src/components/BurgerIngredients/BurgerIngredients.jsx
>    const [current, setCurrent] = React.useState('one')
- [X ]

2021-06-29 14:06 UTC, Some-0ne-Else commented on src/components/IngredientsList/IngredientsList.jsx
>    const filterByType = (type) => {
Исправлено

2021-06-29 14:12 UTC, Some-0ne-Else commented on src/components/Modal/Modal.jsx
> +function Modal({ title, isOpen, onClose, children }) {
Исправлено

2021-06-29 14:12 UTC, Some-0ne-Else commented on src/components/ModalOverlay/ModalOverlay.jsx
> +        <div onClick={(e)=> onClose(e)} className={styles.overlay}></div>
Точно)

2021-06-29 14:12 UTC, Some-0ne-Else commented on src/components/Modal/Modal.jsx
> +        <div className={isOpen ? `${styles.modal} ${styles.modal_opened}` : `${styles.modal}`}>
Исправлено

2021-06-29 21:15 UTC, SmilingJey commented on src/components/BurgerIngredients/BurgerIngredients.jsx
>    const [current, setCurrent] = React.useState('one')
в рамках такой простой задачи и при учете, что здесь нет перерендера при скроле нет существенной разницы, но на практике рефы предпочтительнее

2021-06-29 21:27 UTC, SmilingJey approved these changes
Вы отлично поработали над проектом, все замечания исправлены

Но отметил еще несколько мест над которыми нужно поработать, особое внимание обратите на замечание в ModalOverlay, там теперь createPortal лишний

Внизу конструктора появилась полоса 
![Screenshot_63](https://user-images.githubusercontent.com/9317133/123869300-7be68400-d939-11eb-8ecd-c14de2d3d244.png)

Не забывайте следить за форматированием кода, используйте автоформатирование т.к. проблемы с форматированием плохой тон

Так же можно обернуть компоненты в React.memo, что позволяет сократить количество лишних рендеров и улучшить производительность

Например:

```
const SomeComponent = () => {
  return (
     ...........
  );
};

export default React.memo(SomeComponent);
```

В остальном все отлично, успехов в дальнейшем обучении!

2021-06-29 21:27 UTC, SmilingJey commented on src/components/AppHeader/AppHeader.jsx
>          <NavigationElement component={BurgerIcon} type='primary' text='Конструктор' onClick={handleConstructor}/>
**Можно лучше**

нарушено форматирование кода - проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Практически все современные редакторы умеют автоматически форматировать код. В vscode для этого **достаточно нажать F1 и в выпадающем списке выбрать пункт Format Document**.
 Постарайтесь использовать автоматическое форматирование, это сильно экономит время, а Ваш код будет всегда красив. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

2021-06-29 21:27 UTC, SmilingJey commented on src/components/ConstructorSummary/ConstructorSummary.jsx
> +function ConstructorSummary({total, openModal }) {
**Надо исправить**

опишите propTypes для компонента

2021-06-29 21:27 UTC, SmilingJey commented on src/components/ModalOverlay/ModalOverlay.jsx
> +    return ReactDOM.createPortal((
**Надо исправить**

здесь уже не нужен портал т.к. оверлей рендерится внутри Modal, который и так в портале

2021-06-29 21:27 UTC, SmilingJey commented on src/components/OrderDetails/OrderDetails.jsx
> +        <div className={styles.orderdetails}>
**Можно лучше**

здесь так же нарушено форматирование кода

2021-06-30 10:19 UTC, Some-0ne-Else commented on src/components/AppHeader/AppHeader.jsx
>          <NavigationElement component={BurgerIcon} type='primary' text='Конструктор' onClick={handleConstructor}/>
Не работал husky -(

2021-06-30 10:21 UTC, Some-0ne-Else commented on src/components/ConstructorSummary/ConstructorSummary.jsx
> +function ConstructorSummary({total, openModal }) {
Исправлено

2021-06-30 11:09 UTC, Some-0ne-Else commented on src/components/ModalOverlay/ModalOverlay.jsx
> +    return ReactDOM.createPortal((
Точно)

2021-06-30 11:09 UTC, Some-0ne-Else commented on src/components/OrderDetails/OrderDetails.jsx
> +        <div className={styles.orderdetails}>
Исправлено

2021-06-30 11:09 UTC, merged